### ISSUE TITLE
Add support for macOS Catalina

### ISSUE THREAD

**Issue by ediskrad73** [serban/menubar-ticker#3]
Will this be updated for Catalina & the "new" music app?

**Comment by serban** [comment]
Sure, it should be easy enough. I will not be upgrading to Catalina before the official release is out, so please stay tuned.

**Comment by ediskrad73** [comment]
any update on a new version? thanks!

**Comment by serban** [comment]
I have not upgraded to Catalina yet. Have you tried menubar-ticker 1.0.0 on Catalina and can you confirm that it does not work?

**Comment by ediskrad73** [comment]
yes, all i am seeing is the music note on the menubar.

**Comment by serban** [comment]
Makes sense. Thanks for confirming! I will update and close this issue when I've had a chance to install Catalina and update the code to work with the new apps.

**Comment by ediskrad73** [comment]
great, thank you!!

**Comment by ediskrad73** [comment]
*bump* 

have you had the chance to work on this yet? i really miss using it in my meubar. thanks!

**Comment by serban** [comment]
Unfortunately, Apple does not support Catalina on my 2011 iMac, and Catalina has not yet been approved for use on my work machine. I don't currently have the means to make the changes for the upgrade.

When I do, you will be the first to know. Please hang tight. :-)

**Comment by robinmacharg** [comment]
I've had a quick look into this.  iTunes.app has been renamed to Music.app (and now lives via firmlinks in `/System/Applications`).  I've generated and included the new header file (with the usual `sdef | sdp` dance).  Methods and properties seem to have simply moved from `iTunesWhatever` to `musicWhatever`.  I've added appropriate extra logic following the iTunes example.  However... While I  can see the Music application is running it doesn't provide a correct state (always 0) or any currentTrack info (all values appear nil).  I've not yet had a chance to dig into the extra restrictions Catalina imposes, and the various plist/entitlements that need to be applied but thought I'd share findings thus far.  I'd also like to get the ticker running  again if possible.

**Comment by serban** [comment]
Wow, thanks for looking into this! Happy to accept your pull request.

**Comment by serban** [comment]
@ediskrad73 @petebocken

Folks, I am pleased to announce the release of [v1.1.0](https://github.com/serban/menubar-ticker/releases/tag/v1.1.0) with support for macOS Catalina. Big shout out to @robinmacharg for actually doing all the work to make this happen.

Enjoy!
