### ISSUE TITLE
Does not work with macOS 10.15 Catalina

### ISSUE THREAD

**Issue by petebocken** [serban/menubar-ticker#4]
App launches and runs just fine, but does not display track information for the new Apple Music app in macOS 10.15 Catalina.

**Comment by serban** [comment]
Thanks for the heads-up. This is a known issue. Hope to get around to it any day now...

https://github.com/serban/menubar-ticker/issues/3#issuecomment-551895897

**Comment by serban** [comment]
Duplicate of #3
