### ISSUE TITLE
A Spotify update seems to have stopped this from working

### ISSUE THREAD

**Issue by PaulDoesDev** [serban/menubar-ticker#6]
A few weeks ago I noticed this no longer seemed to work with Spotify. Still works perfectly with Music. Thought I'd let you know.

**Comment by petebocken** [comment]
I am also seeing issues. Spotify 1.1.33.569.gced9e0f5 on Catalina 10.15.4.

The track info will show up for a second then disappear or sometimes display just the artist.

See recording: https://p110.p2.n0.cdn.getcloudapp.com/items/7Ku09xZR/Screen%20Shot%202020-05-20%20at%2015.25.37.gif?v=f0066c1714695edaa8fd7549e43aefeb

**Comment by petebocken** [comment]
Feels like it's more stable (or maybe working 100%) on 1.1.34.694.gac68a2b3. @PaulDoesDev how's yours?

**Comment by KarboniteKream** [comment]
It works fine for me on `1.1.34.694.gac68a2b3` as well.

**Comment by serban** [comment]
Hey, folks.

I also noticed this issue a couple months ago, and it seems to have resolved itself. Looks like Spotify fixed the issue in May:

https://community.spotify.com/t5/Spotify-for-Developers/Apple-OSA-script-not-returning-playback-information-for-new/td-p/4940507

For reference, see issue #2 for another instance of Spotify breaking Menu Bar Ticker.

**Comment by liorazi** [comment]
Not working with: Spotify for macOS (Intel) 1.1.71.560.gc21c3367 on macOS Monterey 12.0.1
(Music app works well)

**Comment by serban** [comment]
Thanks for the report. Looks like 1.1.71.560.gc21c3367 still works in Big Sur. I'll take a look when I upgrade to Monterey.

**Comment by liorazi** [comment]
> Not working with: Spotify for macOS (Intel) 1.1.71.560.gc21c3367 on macOS Monterey 12.0.1 (Music app works well)

Update: It did popup for the Spotify permission after restart. (not sure if that's how it was before)
