### ISSUE TITLE
Does not work with Podcasts.app in Catalina 10.15.7

### ISSUE THREAD

**Issue by ryantargz** [serban/menubar-ticker#7]
I love this app -- but it does not seem to support displaying podcast info when playing something from Podcasts.app

Any chance of that getting fixed, or added as a feature? Thanks!

Running:
MenubarTicker.app -- Version 1.1.0
Podcasts.app -- Version 1.0.0 (1440.4)
macOS Catalina -- Version 10.15.7 (19H2)

**Comment by serban** [comment]
Hey, Ryan.

I looked into this a while back. Unfortunately, Podcasts.app does not provide scripting support as do iTunes and Music.app, and I didn't spend too much time trying to find a clever way to get the metadata from Podcasts. If Apple provides scripting support for Podcasts in a future update, it should be straightforward to support it in Menu Bar Ticker.

Do you know of any other apps that read metadata from Podcasts? If so, I could try to find out how they do it.
